# Generated by Django 5.2 on 2025-04-13 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='admin_dashboard.group'),
        ),
    ]
