# Generated by Django 5.2 on 2025-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_announcement_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='timetable',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
