# Generated by Django 5.2 on 2025-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
